# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.2'

gem 'rails', '6.1.4'

# gem 'bcrypt'
gem 'bootsnap', require: false
# gem 'image_processing'
# gem 'jbuilder'
gem 'pg'
gem 'puma'
gem 'sass-rails'
gem 'turbolinks'
gem 'webpacker'

gem 'appsignal'
gem 'clockwork'
gem 'faraday'
gem 'lograge'
gem 'nilify_blanks'
gem 'sidekiq'
# gem 'stripe'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'listen'
  gem 'rack-mini-profiler'
  gem 'spring'
  gem 'web-console'

  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'

  gem 'minitest-spec-rails'
  gem 'mocha'
  gem 'simplecov', require: false
  gem 'webmock', require: false
end
