web: bundle exec puma -C config/puma.rb
worker: bundle exec sidekiq -C config/sidekiq.yml
clock: bundle exec clockwork config/clock.rb
release: bundle exec rake db:migrate
log: tail -f log/development.log
